# Initiation à Python

Ce document présente une introduction à Python, couvrant les concepts de base, les types de données, les structures de contrôle, les fonctions, et l'importation de modules.

---

## 1. Qu'est-ce que Python ?

Python est un langage de programmation interprété, polyvalent et facile à apprendre. Il est largement utilisé pour :
- Le développement web.
- L'analyse de données.
- L'intelligence artificielle.
- Le calcul scientifique.

Python se distingue par sa syntaxe simple, qui facilite la lecture et la maintenance du code.

**Exemple** : Un programme simple pour afficher un message.  
+++python
print("Bienvenue dans l'apprentissage de Python!")
+++

**Exercice** : Écrivez un programme Python pour afficher votre prénom.

---
## 2. Types de données primitifs

Les types de données primitifs en Python sont les types de base qui permettent de stocker et manipuler des valeurs fondamentales. Les principaux types primitifs incluent :  

1. **int** : utilisé pour représenter des nombres entiers, positifs ou négatifs.  
2. **float** : utilisé pour représenter des nombres décimaux (nombres à virgule flottante).  
3. **str** : utilisé pour représenter des chaînes de caractères.  
4. **bool** : utilisé pour représenter des valeurs booléennes, qui peuvent être soit `True` soit `False`.  

### Explications et exemples pour chaque type

#### **int (entiers)**
Un entier est un nombre sans partie décimale.  
**Exemple** :  
+++python
x = 42  # int
print(x)           # Affiche : 42
print(type(x))     # Affiche : <class 'int'>
+++

#### **float (nombres décimaux)**
Un float est un nombre contenant une partie décimale.  
**Exemple** :  
+++python
y = 3.14159  # float
print(y)             # Affiche : 3.14159
print(type(y))       # Affiche : <class 'float'>
+++

#### **str (chaînes de caractères)**
Une chaîne de caractères est une séquence de lettres, chiffres ou symboles, encadrée par des guillemets simples ou doubles.  
**Exemple** :  
+++python
z = "Python est génial!"  # str
print(z)             # Affiche : Python est génial!
print(type(z))       # Affiche : <class 'str'>
+++

#### **bool (valeurs booléennes)**
Une valeur booléenne représente une condition qui est soit vraie (`True`), soit fausse (`False`).  
**Exemple** :  
+++python
is_fun = True  # bool
print(is_fun)           # Affiche : True
print(type(is_fun))     # Affiche : <class 'bool'>
+++

### Manipulation combinée des types primitifs

Il est possible d'utiliser différents types primitifs dans un même programme. Voici un exemple combinant les quatre types :  
+++python
# Déclaration des variables
x = 7                 # int
y = 2.5               # float
z = "Apprendre Python"  # str
is_valid = True       # bool

# Affichage des types et des valeurs
print(f"Valeur de x : {x}, Type : {type(x)}")
print(f"Valeur de y : {y}, Type : {type(y)}")
print(f"Valeur de z : {z}, Type : {type(z)}")
print(f"Valeur de is_valid : {is_valid}, Type : {type(is_valid)}")
+++

### Exercice

1. Déclarez une variable pour chaque type de données primitif mentionné.
2. Affichez à la fois la valeur et le type de chaque variable.

---

## 3. Opérations mathématiques

Python prend en charge plusieurs opérations mathématiques de base et avancées, qui sont utilisées pour manipuler des nombres. Ces opérations incluent :  

1. **Addition (`+`)** : pour additionner deux nombres.  
2. **Soustraction (`-`)** : pour soustraire un nombre d'un autre.  
3. **Multiplication (`*`)** : pour multiplier deux nombres.  
4. **Division (`/`)** : pour diviser un nombre par un autre (retourne un float).  
5. **Modulo (`%`)** : pour obtenir le reste d'une division entière.  
6. **Puissance (`**`)** : pour élever un nombre à une puissance donnée.  
7. **Division entière (`//`)** : pour obtenir le quotient d'une division entière (sans le reste).  

### Explications et exemples

#### **Opérations de base**
**Exemple** :  
+++python
a = 10
b = 3

print(a + b)  # Addition : Affiche 13
print(a - b)  # Soustraction : Affiche 7
print(a * b)  # Multiplication : Affiche 30
print(a / b)  # Division : Affiche 3.3333333333333335
+++

#### **Modulo et division entière**
**Exemple** :  
+++python
a = 10
b = 3

print(a % b)  # Modulo : Affiche 1 (reste de la division)
print(a // b) # Division entière : Affiche 3 (quotient entier)
+++

#### **Puissance**
**Exemple** :  
+++python
a = 2
b = 5

print(a ** b)  # Puissance : Affiche 32 (2^5)
+++

### Utilisation combinée des opérations

Les opérations peuvent être combinées pour effectuer des calculs complexes :  
+++python
x = 5
y = 2

# Calculs combinés
resultat = (x ** 2 + y) / (x - y)
print(f"Le résultat du calcul est : {resultat}")
+++

### Exercice

1. Écrivez un programme pour demander deux nombres à l'utilisateur.
2. Calculez et affichez la somme, la différence, le produit, le quotient et le reste de leur division.



## 4. Types de données composites

Les types de données composites permettent de stocker et de manipuler des collections d'éléments. Python propose plusieurs types composites, chacun ayant ses propres caractéristiques :  

1. **list** : une collection ordonnée et modifiable.  
2. **tuple** : une collection ordonnée mais immuable.  
3. **dict** : une collection non ordonnée de paires clé-valeur.  
4. **set** : une collection non ordonnée d'éléments uniques.  

### Explications et exemples pour chaque type

#### **list (listes)**
Une liste est une collection ordonnée d'éléments. Les listes sont modifiables : vous pouvez ajouter, supprimer ou modifier des éléments.  
**Exemple** :  
+++python
# Déclaration d'une liste
ma_liste = [10, 20, 30, 40, 50]

# Accès aux éléments
print(ma_liste[0])    # Premier élément : Affiche 10
print(ma_liste[-1])   # Dernier élément : Affiche 50

# Modification d'un élément
ma_liste[2] = 35
print(ma_liste)       # Affiche : [10, 20, 35, 40, 50]

# Ajout d'un élément
ma_liste.append(60)
print(ma_liste)       # Affiche : [10, 20, 35, 40, 50, 60]
+++

#### **tuple (tuples)**
Un tuple est une collection ordonnée comme une liste, mais il est immuable : ses éléments ne peuvent pas être modifiés après sa création.  
**Exemple** :  
+++python
# Déclaration d'un tuple
mon_tuple = (1, 2, 3, 4, 5)

# Accès aux éléments
print(mon_tuple[1])    # Deuxième élément : Affiche 2

# Tentative de modification (provoque une erreur)
# mon_tuple[1] = 10     # Erreur : TypeError
+++

#### **dict (dictionnaires)**
Un dictionnaire est une collection de paires clé-valeur. Chaque clé doit être unique, et les valeurs peuvent être de tout type.  
**Exemple** :  
+++python
# Déclaration d'un dictionnaire
mon_dict = {"nom": "Python", "version": 3.10, "langage": "programming"}

# Accès à une valeur via une clé
print(mon_dict["nom"])        # Affiche : Python

# Modification d'une valeur
mon_dict["version"] = 3.11
print(mon_dict)               # Affiche : {'nom': 'Python', 'version': 3.11, 'langage': 'programming'}

# Ajout d'une nouvelle clé-valeur
mon_dict["créateur"] = "Guido van Rossum"
print(mon_dict)               # Affiche toutes les clés et leurs valeurs
+++

#### **set (ensembles)**
Un ensemble est une collection non ordonnée contenant des éléments uniques. Les doublons sont automatiquement supprimés.  
**Exemple** :  
+++python
# Déclaration d'un ensemble
mon_set = {1, 2, 3, 4, 4, 5}

print(mon_set)   # Affiche : {1, 2, 3, 4, 5} (les doublons sont supprimés)

# Ajout d'un élément
mon_set.add(6)
print(mon_set)   # Affiche : {1, 2, 3, 4, 5, 6}

# Suppression d'un élément
mon_set.remove(3)
print(mon_set)   # Affiche : {1, 2, 4, 5, 6}
+++

### Comparaison des types composites

| Type    | Ordonné | Modifiable | Doublons autorisés | Exemple                              |
|---------|---------|------------|--------------------|--------------------------------------|
| `list`  | Oui     | Oui        | Oui                | `[1, 2, 3]`                          |
| `tuple` | Oui     | Non        | Oui                | `(1, 2, 3)`                          |
| `dict`  | Non     | Oui        | Non (pour les clés) | `{"a": 1, "b": 2}`                   |
| `set`   | Non     | Oui        | Non                | `{1, 2, 3}`                          |

### Exercices

1. Créez une liste contenant cinq nombres entiers et calculez leur somme.  
2. Créez un tuple contenant les noms de trois de vos matières préférées. Essayez d'accéder au deuxième élément.  
3. Déclarez un dictionnaire avec trois clés : `"nom"`, `"âge"`, et `"ville"`. Ajoutez une quatrième clé `"pays"` avec une valeur de votre choix.  
4. Créez un ensemble avec des nombres de 1 à 10, mais incluez des doublons. Affichez l'ensemble après la déclaration.  
## 5. Bloc `if`, `else`, `elif`

Les blocs conditionnels permettent d'exécuter du code en fonction de certaines conditions logiques. Ils sont basés sur des expressions qui évaluent à `True` ou `False`.

### Structure générale
La structure d'un bloc conditionnel en Python est la suivante :  
- Le mot-clé `if` vérifie une première condition.
- Le mot-clé `elif` (optionnel) permet de vérifier des conditions alternatives.
- Le mot-clé `else` (optionnel) exécute un bloc si aucune condition précédente n'est vraie.

### Syntaxe
Chaque bloc doit être indenté pour indiquer les instructions associées.

**Syntaxe générale** :  
+++python
if condition1:
    # Bloc exécuté si condition1 est vraie
elif condition2:
    # Bloc exécuté si condition1 est fausse et condition2 est vraie
else:
    # Bloc exécuté si aucune condition n'est vraie
+++

### Exemple 1 : Vérification de la nature d'un nombre
+++python
x = 10

if x > 0:
    print("x est positif")
elif x == 0:
    print("x est zéro")
else:
    print("x est négatif")
+++

### Exemple 2 : Vérification d'une catégorie d'âge
+++python
age = 25

if age < 18:
    print("Mineur")
elif 18 <= age <= 65:
    print("Adulte")
else:
    print("Sénior")
+++

### Comparateurs et opérateurs logiques
Les blocs conditionnels utilisent des comparateurs et opérateurs pour formuler des conditions :  
- **Comparateurs** :  
  - `==` : égal à  
  - `!=` : différent de  
  - `<`, `>`, `<=`, `>=` : comparaisons numériques  

- **Opérateurs logiques** :  
  - `and` : toutes les conditions doivent être vraies.  
  - `or` : au moins une condition doit être vraie.  
  - `not` : inverse la valeur logique d'une condition.

**Exemple avec plusieurs conditions** :  
+++python
score = 85

if score > 90:
    print("Excellent")
elif score > 70 and score <= 90:
    print("Bon")
else:
    print("Peut mieux faire")
+++

### Exercices

1. Écrivez un programme qui vérifie si un nombre entier est **pair** ou **impair**.  
2. Demandez à l'utilisateur son âge et affichez un message pour indiquer s'il est **mineur**, **adulte**, ou **sénior**.  
3. Écrivez un programme qui prend une note (sur 100) et affiche :  
   - "A" si la note est supérieure ou égale à 90,  
   - "B" si elle est entre 80 et 89,  
   - "C" si elle est entre 70 et 79,  
   - "F" sinon.  

## 6. Boucles `for` et `while`

Les boucles permettent de répéter l'exécution d'un bloc de code tant que certaines conditions sont remplies ou pour un nombre déterminé d'itérations. Python propose principalement deux types de boucles : `for` et `while`.

### Boucle `for`

La boucle `for` est utilisée pour itérer sur des éléments d'une séquence, comme une liste, un tuple, une chaîne de caractères ou une plage de nombres. La structure de base est la suivante :

**Syntaxe générale** :  
+++python
for variable in séquence:
    # Bloc de code à exécuter pour chaque élément de la séquence
+++

**Exemple** :  
+++python
for i in range(5):
    print(i)
+++
Cet exemple utilise la fonction `range(5)`, qui génère les nombres de 0 à 4. La boucle `for` itère sur ces valeurs et les affiche successivement.

### La fonction `range()`
La fonction `range()` est utilisée pour générer une séquence de nombres. Elle peut être utilisée de différentes manières :
- `range(stop)` : génère de 0 à `stop-1`.
- `range(start, stop)` : génère de `start` à `stop-1`.
- `range(start, stop, step)` : génère de `start` à `stop-1`, en incrémentant de `step`.

**Exemple** :  
+++python
for i in range(2, 10, 2):
    print(i)
+++
Cet exemple affiche les nombres pairs de 2 à 8.

### Boucle `while`

La boucle `while` continue de s'exécuter tant que la condition spécifiée est `True`. Elle est utile pour les situations où le nombre d'itérations n'est pas connu à l'avance.

**Syntaxe générale** :  
+++python
while condition:
    # Bloc de code à exécuter tant que la condition est vraie
    instruction(s) de modification de la condition
+++

**Exemple** :  
+++python
n = 0
while n < 5:
    print(n)
    n += 1
+++
Cet exemple initialise `n` à 0 et incrémente `n` à chaque itération. La boucle continue jusqu'à ce que `n` atteigne 5, moment où la condition `n < 5` devient `False` et la boucle s'arrête.

### Utilisation de la boucle `while` avec une condition de sortie

Il est possible d'utiliser des instructions comme `break` pour quitter la boucle prématurément et `continue` pour passer à l'itération suivante sans exécuter le reste du code dans la boucle.

**Exemple avec `break`** :  
+++python
x = 0
while x < 10:
    if x == 5:
        break  # Arrête la boucle lorsque x est égal à 5
    print(x)
    x += 1
+++

**Exemple avec `continue`** :  
+++python
for i in range(6):
    if i % 2 == 0:
        continue  # Passe à l'itération suivante si i est pair
    print(i)
+++

### Exercices

1. Utilisez une boucle `for` pour afficher les carrés des nombres de 1 à 10.
2. Écrivez un programme qui utilise une boucle `while` pour afficher les valeurs de 10 à 1 en décrémentant de 1 à chaque itération.
3. Créez un programme qui affiche tous les nombres pairs de 0 à 20 en utilisant une boucle `while`.

## 7. Fonctions

Les fonctions en Python permettent de regrouper des blocs de code afin de les rendre réutilisables et modulaires. Elles facilitent la structuration du code et la réduction de la duplication.

### Déclaration d'une fonction
Pour définir une fonction en Python, on utilise le mot-clé `def` suivi du nom de la fonction, des parenthèses et de deux points. Les instructions de la fonction sont indentées.

**Syntaxe générale** :  
+++python
def nom_fonction(paramètre1, paramètre2, ...):
    # Bloc de code
    return résultat
+++

### Exemple : Fonction simple
+++python
def carre(x):
    return x ** 2

print(carre(5))  # Affiche 25
+++
La fonction `carre` prend un paramètre `x` et retourne son carré. Le mot-clé `return` permet de renvoyer un résultat à l'appelant de la fonction.

### Types de fonctions

#### 1. Fonction sans paramètres
Une fonction qui ne prend aucun paramètre peut être définie pour exécuter un bloc de code de manière autonome.

**Exemple** :  
+++python
def salutation():
    print("Bonjour, bienvenue dans le monde de Python!")

salutation()  # Affiche "Bonjour, bienvenue dans le monde de Python!"
+++

#### 2. Fonction avec paramètres
Les fonctions peuvent prendre un ou plusieurs paramètres qui sont utilisés à l'intérieur de la fonction.

**Exemple** :  
+++python
def addition(a, b):
    return a + b

print(addition(3, 4))  # Affiche 7
+++

#### 3. Fonction avec valeur de retour
Une fonction peut retourner un résultat à l'aide du mot-clé `return`. Cela permet de capturer le résultat dans une variable ou de l'utiliser directement.

**Exemple** :  
+++python
def multiplication(x, y):
    return x * y

resultat = multiplication(4, 5)
print(resultat)  # Affiche 20
+++

#### 4. Fonction avec paramètres par défaut
Il est possible de spécifier des valeurs par défaut pour certains paramètres. Si ces paramètres ne sont pas fournis lors de l'appel de la fonction, les valeurs par défaut sont utilisées.

**Exemple** :  
+++python
def saluer(nom="inconnu"):
    print(f"Bonjour, {nom}!")

saluer("Alice")  # Affiche "Bonjour, Alice!"
saluer()         # Affiche "Bonjour, inconnu!"
+++

#### 5. Fonction avec paramètres variables
Pour accepter un nombre variable d'arguments, Python utilise les symboles `*args` pour les arguments positionnels et `**kwargs` pour les arguments nommés.

**Exemple avec `*args`** :  
+++python
def somme(*args):
    return sum(args)

print(somme(1, 2, 3, 4))  # Affiche 10
+++

**Exemple avec `**kwargs`** :  
+++python
def afficher_détails(**kwargs):
    for clé, valeur in kwargs.items():
        print(f"{clé}: {valeur}")

afficher_détails(nom="Alice", age=25, ville="Paris")
# Affiche :
# nom: Alice
# age: 25
# ville: Paris
+++

### Utilisation de la fonction `lambda`
Les fonctions lambda sont des fonctions anonymes définies à l'aide du mot-clé `lambda`. Elles peuvent prendre plusieurs arguments mais n'ont pas de nom et ne contiennent généralement qu'une seule expression.

**Exemple** :  
+++python
carre_lambda = lambda x: x ** 2
print(carre_lambda(6))  # Affiche 36
+++

### Appel de la fonction
Pour appeler une fonction, il suffit de spécifier son nom et de passer les arguments requis.

**Exemple** :  
+++python
def saluer(nom):
    print(f"Bonjour, {nom}!")

saluer("Bob")  # Affiche "Bonjour, Bob!"
+++

### Exercice

1. Écrivez une fonction qui prend un nom comme paramètre et affiche un message de bienvenue.
2. Créez une fonction qui calcule la factorielle d'un nombre donné.
3. Écrivez une fonction qui prend une liste de nombres en paramètres et retourne la somme des nombres pairs de cette liste.
4. Utilisez une fonction lambda pour créer une fonction qui double un nombre et testez-la avec quelques valeurs.

## 8. Importation de modules

L'importation de modules en Python permet d'étendre les fonctionnalités du langage et d'utiliser des bibliothèques de fonctions et de classes déjà développées. Cela permet d'accéder à des outils puissants pour le calcul, la manipulation de données, la création de graphiques, etc.

### Importation de modules standards

Python est livré avec une bibliothèque standard qui contient de nombreux modules intégrés, tels que `math`, `random`, `datetime`, etc. Pour utiliser ces modules, il suffit de les importer à l'aide de la commande `import`.

**Syntaxe générale** :  
+++python
import nom_du_module
+++

### Exemple d'importation et d'utilisation de `math`

Le module `math` fournit des fonctions mathématiques avancées, comme la racine carrée, les fonctions trigonométriques et les constantes mathématiques telles que `math.pi`.

**Exemple** :  
+++python
import math

print(math.sqrt(16))  # Affiche 4.0, la racine carrée de 16
print(math.pi)        # Affiche la valeur de pi (approximativement 3.14159)
+++

### Importation de fonctions spécifiques

Pour importer une fonction spécifique d'un module, on peut utiliser la syntaxe `from ... import ...`. Cela permet de ne pas avoir à préfixer le nom du module à chaque utilisation de la fonction.

**Syntaxe générale** :  
+++python
from nom_du_module import fonction
+++

**Exemple** :  
+++python
from math import sqrt, pi

print(sqrt(25))  # Affiche 5.0
print(pi)        # Affiche 3.14159
+++

### Importation avec alias

Il est possible d'importer un module sous un alias pour simplifier son utilisation, surtout lorsqu'il a un nom long ou lorsqu'on souhaite éviter des conflits de noms.

**Syntaxe générale** :  
+++python
import nom_du_module as alias
+++

**Exemple** :  
+++python
import numpy as np

# Utilisation de la fonction `array` de `numpy`
tableau = np.array([1, 2, 3, 4])
print(tableau)  # Affiche [1 2 3 4]
+++

### Exemple d'importation de modules tiers

Python permet également d'importer des modules tiers qui ne font pas partie de la bibliothèque standard. Ces modules doivent être installés à l'aide de `pip`, le gestionnaire de paquets de Python.

**Installation avec `pip`** :  
+++bash
pip install nom_du_module
+++

**Exemple** : Importation du module `pandas` pour la manipulation de données.
+++python
import pandas as pd

# Création d'un DataFrame simple
data = {'Nom': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print(df)
+++

### Importation de tous les éléments d'un module

Il est possible d'importer tous les éléments d'un module en utilisant la syntaxe `from ... import *`, mais cette pratique est déconseillée car elle peut entraîner des conflits de noms et rendre le code moins lisible.

**Syntaxe** :  
+++python
from nom_du_module import *
+++

**Exemple** :  
+++python
from math import *

print(sqrt(49))  # Affiche 7.0
print(factorial(5))  # Affiche 120
+++

### Exercice

1. Importez le module `random` et utilisez-le pour générer un nombre aléatoire entre 1 et 100.
2. Importez la fonction `sin` du module `math` et affichez le sinus de 45 degrés (en radians).
3. Utilisez le module `datetime` pour afficher la date et l'heure actuelles.

---












# Initiation à Python

**Cours** : [_Analyse Numérique pour SV_](https://moodle.epfl.ch/course/info.php?id=) (MATH-2xx)  
**Professeur** : _Simone Deparis_

SSV, BA4, 2020  

Adapté du tutoriel Python `CS228` par [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) et [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335) ainsi que de la version du Prof. Felix Naef pour le cours BIO-341.

## Introduction

Python est un excellent langage de programmation généraliste en soi, mais avec l'aide de quelques bibliothèques populaires (numpy, scipy, matplotlib), il devient un environnement puissant pour le calcul scientifique.

Nous ne supposons pas que beaucoup d'entre vous aient une expérience préalable avec Python et numpy ; cette section servira de cours accéléré à la fois sur le langage de programmation Python et sur son utilisation pour le calcul scientifique.

Certains d'entre vous ont peut-être des connaissances préalables en Matlab, auquel cas nous vous recommandons également la page numpy pour les utilisateurs de Matlab (https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html).

Dans ce tutoriel, nous aborderons :

- **Python de base** : Types de données de base (conteneurs, listes, dictionnaires, ensembles, tuples), fonctions.
- **Numpy** : Tableaux, indexation de tableaux, types de données, mathématiques sur les tableaux, diffusion (broadcasting).
- **Matplotlib** : Graphiques, sous-graphiques, images.

## Bases de Python

Python est un langage de programmation de haut niveau, dynamiquement typé et multiparadigme. Le code Python est souvent considéré comme proche du pseudocode, car il permet d'exprimer des idées très puissantes en quelques lignes de code tout en restant très lisible. Par exemple, voici une implémentation de l'algorithme classique de tri rapide (quicksort) en Python :

:::python
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3, 6, 8, 10, 1, 2, 1]))
:::

### Versions de Python

Il existe actuellement deux versions de Python prises en charge : 2.7 et 3.7. De manière quelque peu déroutante, Python 3.0 a introduit de nombreuses modifications non rétrocompatibles avec le langage, ce qui fait que le code écrit pour 2.7 peut ne pas fonctionner sous 3.7 et vice versa. Pour ce cours, tout le code utilisera Python 3.7.

Vous pouvez vérifier votre version de Python en ligne de commande en exécutant `python --version`.

### Types de données de base

#### Nombres

Les entiers et les nombres à virgule flottante fonctionnent comme dans d'autres langages :

:::python
x = 3
print(x, type(x))
:::

:::python
print(x + 1)  # Addition
print(x - 1)  # Soustraction
print(x * 2)  # Multiplication
print(x**2)   # Exponentiation
:::

:::python
x += 1
print(x)  # Affiche "4"
x *= 2
print(x)  # Affiche "8"
:::

:::python
y = 2.5
print(type(y))  # Affiche "<type 'float'>"
print(y, y + 1, y * 2, y ** 2)  # Affiche "2.5 3.5 5.0 6.25"
:::

Notez que, contrairement à de nombreux langages, Python n'a pas d'opérateurs d'incrémentation (x++) ou de décrémentation (x--).


#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [ ]:
t, f = True, False
print(type(t)) # Prints "<type 'bool'>"

Now we let's look at the operations:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

#### Strings

In [ ]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print(hello, len(hello))

In [ ]:
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"

String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

#### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

In [ ]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

In [ ]:
xs.append('bar') # Add a new element to the end of the list
print(xs)  

In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs) 

#### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
nums = list(range(5))    # range is a built-in function that creates an interator of integers. 
                         #It has to be explicitely converted to a list to do slicing
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])     # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

#### Loops

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(idx + 1, animal)

#### List comprehensions:

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

You can make this code simpler using a list comprehension:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

List comprehensions can also contain conditions:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

#### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

In [ ]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

In [ ]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

In [ ]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

In [ ]:
del(d['fish'])        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

It is easy to iterate over the keys in a dictionary:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A', animal, 'has', legs, 'legs')

If you want access to keys and their corresponding values, use the items method:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
     print('A', animal, 'has', legs, 'legs')

Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

#### Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"

In [ ]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

In [ ]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))       
animals.remove('cat')    # Remove an element from a set
print(len(animals))       

_Loops_: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print(idx + 1,':', animal)
# Prints "1 : fish", "2 : dog", "3 : cat"

Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [ ]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

#### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t]) 
print(d[(1, 2)])

In [ ]:
t[0] = 1

### Functions

Python functions are defined using the `def` keyword. For example:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

We will often define functions to take optional keyword arguments, like this:

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO', name.upper())
    else:
        print('Hello', name)

hello('Bob')
hello('Fred', loud=True)

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

In [ ]:
print(b.shape)                 
print(b[0, 0], b[0, 1], b[1, 0])

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c) 

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot or @ is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(v@w)
print(np.dot(v, w))

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print(x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v) 
print(v.T)

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)


In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)


In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.

print(x + np.reshape(w, (2, 1)))


In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:

print(x * 2)


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

## Matplotlib

Matplotlib is a plotting library. In this section give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

In [ ]:
import matplotlib.pyplot as plt


By running this special iPython command, we will be displaying plots inline:

In [ ]:
%matplotlib inline


### Plotting

The most important function in `matplotlib` is plot, which allows you to plot 2D data. Here is a simple example:

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)
plt.show()


With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()


### Subplots 

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()
